export const AUTH_LOGIN='AUTH_LOGIN';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_ROLE = 'SET_ROLE';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';

export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';

export const VIEW_PRODUCT='VIEW_PRODUCT';
export const SET_PRODUCTDATA='SET_PRODUCTDATA';
export const SET_PRODUCTVARIATION='SET_PRODUCTVARIATION';
export const SET_PRODUCTID='SET_PRODUCTID';

export const VIEW_CART = 'VIEW_CART';
export const SET_CART = 'SET_CART';
export const SET_CART_DETAILS='SET_CART_DETAILS';

export const SET_CUSTOMER_ACCOUNT='SET_CUSTOMER_ACCOUNT';
export const SET_CUSTOMER_ADDRESS='SET_CUSTOMER_ADDRESS';
export const SET_SELLER_ADDRESS='SET_SELLER_ADDRESS';
export const SET_EDIT_ADDRESS_DATA='SET_EDIT_ADDRESS_DATA';

export const SET_CATEGORY_DATA='SET_CATEGORY_DATA';

export const SET_ORDERS='SET_ORDERS';

export const SET_LOGINCLICKED='SETLOGINCLICKED';

export const SET_SELLER_PRODUCT = 'SET_SELLER_PRODUCT';
export const SET_SELLER_PRODUCT_VARIATION = 'SET_SELLER_PRODUCT_VARIATION';
export const SET_METADATA_CATEGORY='SET_METADATA_CATEGORY';

export const ADMIN_VIEW_SELLER = 'ADMIN_VIEW_SELLER';
export const ADMIN_VIEW_CUSTOMER = 'ADMIN_VIEW_CUSTOMER';
export const ADMIN_VIEW_PRODUCT = 'ADMIN_VIEW_PRODUCT';
export const ADMIN_VIEW_CATEGORY = 'ADMIN_VIEW_CATEGORY';
export const ADMIN_VIEW_METADATA= 'ADMIN_VIEW_METADATA';
export const SET_ADMIN_CATEGORY_DATA= 'SET_ADMIN_CATEGORY_DATA';
export const SET_ADMIN_METADATA= 'SET_ADMIN_METADATA';
export const SET_ADMIN_FIELD_VALUES= 'SET_ADMIN_FIELD_VALUES';

export const SET_ERROR='SET_ERROR';
export const SET_ERROR_NULL='SET_ERROR_NULL';

export const SET_MESSAGE='SET_MESSAGE';
export const SET_SUCCESS_FAIL='SET_SUCCESS_FAIL';

export const SET_UPDATE_MESSAGE='SET_UPDATE_MESSAGE';
