export const AUTH_LOGIN='AUTH_LOGIN';
export const AUTH_FAIL='AUTH_FAIL';

export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';

export const VIEW_PRODUCT='VIEW_PRODUCT';
export const SET_PRODUCTDATA='SET_PRODUCTDATA';
export const SET_PRODUCTVARIATION='SET_PRODUCTVARIATION';
export const SET_PRODUCTID='SET_PRODUCTID';

export const VIEW_CART = 'VIEW_CART';
export const SET_CART = 'SET_CART';

export const SET_CUSTOMER_ACCOUNT='SET_CUSTOMER_ACCOUNT';
export const SET_CUSTOMER_ADDRESS='SET_CUSTOMER_ADDRESS';

export const SET_LOGINCLICKED='SETLOGINCLICKED';